### PR TITLE
using typeof instead of instance of and checking for string as there …

### PR DESCRIPTION
**Pull request by McKean**
…were issues passing an object

Ran into some troubles, would be great to get this merged and tagged.

Thanks!

### CODE REVIEW

**Comment by EvasiveXkiller** [comment]
Hello there, thanks for the PR

I have just fixed the repo and now the tests are all passing (long overdue chore :D). Would you please pull the latest commit?

Thanks!

**Comment by Sxxov** [comment]
@McKean could you provide a repro? the only way this could happen in my imagination, is if you passed in an array that has had its prototype swapped out, in which case `forEach` shouldn't exist on it either

**Comment by McKean** [comment]
@Sxxov so basically I get this issue

```
TypeError: str.trim is not a function

      at Function.parse (node_modules/youtube-moosick/node_modules/tough-cookie/lib/cookie.js:457:13)
      at YoutubeMoosick.parseAndSetCookie (node_modules/youtube-moosick/src/YoutubeMoosick.ts:144:4)
      at node_modules/youtube-moosick/src/YoutubeMoosick.ts:102:11
      at YoutubeMoosick.new (node_modules/youtube-moosick/src/YoutubeMoosick.ts:115:10)
```

from
```
import {
  Album,
  Category,
  ContinuableResult,
  YoutubeMoosick,
} from 'youtube-moosick';

export async function queryByBarcode(barcode: string): Promise<Album> {
  const ytms = await YoutubeMoosick.new();
  const response = await ytms.search(barcode, Category.ALBUM);

  return response[0];
}

export async function getReleaseLinkByBarcode(
  barcode: string
): Promise<string> {
  const response = await queryByBarcode(barcode);
  return response.url;
}
```

**Comment by Sxxov** [comment]
@McKean can't seem to reproduce the error on my local machine nor on runkit. could ya show the shape of the `headers['set-cookie']` at the time of error?

if you'd like, i could catch you on discord as well to debug this faster (::

**Comment by McKean** [comment]
@Sxxov thanks for the quick reply, things are busy today, but feel free to invite (McKean#8190)
here's the `set-cookie`
```
'set-cookie': [
        'YSC=UycQ2jKdfdQ; Domain=.youtube.com; Path=/; Secure; HttpOnly; SameSite=none',
        '__Secure-YEC=; Domain=.youtube.com; Expires=Tue, 13-Aug-2019 09:17:18 GMT; Path=/; Secure; HttpOnly; SameSite=lax',
        'VISITOR_INFO1_LIVE=Y8YB5TBksq8; Domain=.youtube.com; Expires=Sat, 05-Nov-2022 09:17:18 GMT; Path=/; Secure; HttpOnly; SameSite=none',
        'CONSENT=PENDING+501; expires=Wed, 08-May-2024 09:17:18 GMT; path=/; domain=.youtube.com; Secure'
      ],
```

**Comment by Sxxov** [comment]
@McKean have added you. currently i suspect `Object.getPrototypeOf(headers['set-cookie']) !== Array.prototype`, which is bizarre, but patchable. i can take over this pr if that turns out to be the case

**Comment by McKean** [comment]
@Sxxov sure feel free, highly appreciated!
Many thanks for the friendly exchange.

**Pull request closed without merging**
